import { CommandModule, ApplicationCommandArguments } from "../types";
import {
    ApplicationCommandOptionType as DiscordApplicationCommandOptionType,
    ApplicationCommandType as DiscordApplicationCommandType,
    RESTPostAPIApplicationCommandsJSONBody
} from 'discord.js';
import path from 'path';
import * as fs from 'fs';

const MODULE_EXTENSIONS = new Set([
    ".ts",
    ".js",
    ".cjs",
    ".mjs"
]);

type CommandTree = {
    [key: string]: CommandModule | CommandTree
};

type ChatInputCommandBody = Extract<RESTPostAPIApplicationCommandsJSONBody, { "description": string }>;
type ChatInputCommandOption = NonNullable<ChatInputCommandBody["options"]>[number];
type SubcommandOption = Extract<ChatInputCommandOption, { "type": DiscordApplicationCommandOptionType.Subcommand }>;
type SubcommandGroupOption = Extract<ChatInputCommandOption, { "type": DiscordApplicationCommandOptionType.SubcommandGroup }>;
type BasicChatInputCommandOption = Exclude<ChatInputCommandOption, SubcommandOption | SubcommandGroupOption>;

export const isCommandModule = (value: CommandModule | CommandTree): value is CommandModule => {
    return typeof value === "object" &&
        value !== null &&
        "command" in value &&
        "callback" in value;
};

export const resolveFilePath = (dirPath: string, moduleName: string, throwWhenNotFound?: boolean) => {
    const possibleFileNames = [
        `${moduleName}.ts`,
        `${moduleName}.js`,
        `${moduleName}.cjs`,
        `${moduleName}.mjs`
    ];

    for (const fileName of possibleFileNames) {
        const filePath = path.join(dirPath, fileName);

        if (fs.existsSync(filePath))
            return filePath;
    }

    if (throwWhenNotFound)
        throw new Error(`Cannot find ${possibleFileNames.join("/")} in the project root.`);

    return;
};

export const getLoadableFiles = (dirPath: string): string[] => {
    const entries = fs.readdirSync(dirPath, { "withFileTypes": true });
    const filePaths: string[] = [];

    for (const entry of entries) {
        const entryPath = path.join(dirPath, entry.name);

        if (entry.isDirectory()) {
            filePaths.push(...getLoadableFiles(entryPath));
            continue;
        }

        if (MODULE_EXTENSIONS.has(path.extname(entry.name)))
            filePaths.push(entryPath);
    }

    return filePaths;
};

export const getModuleKey = (basePath: string, filePath: string) => {
    const relativePath = path.relative(basePath, filePath);
    const parsedPath = path.parse(relativePath);

    return path.join(parsedPath.dir, parsedPath.name).replaceAll("\\", "/");
};

export const insertCommandModule = (tree: CommandTree, commandKey: string, module: CommandModule) => {
    const pathParts = commandKey.split("/");
    let currentNode = tree;

    for (let i = 0; i < pathParts.length; i++) {
        const part = pathParts[i];
        const isLeaf = i === pathParts.length - 1;
        const currentValue = currentNode[part];

        if (isLeaf) {
            if (currentValue)
                throw new Error(`Duplicate command key detected: ${commandKey}`);

            currentNode[part] = module;
            return;
        }

        if (!currentValue) {
            const nextNode: CommandTree = {};
            currentNode[part] = nextNode;
            currentNode = nextNode;
            continue;
        }

        if (isCommandModule(currentValue))
            throw new Error(`Command path collision detected: ${commandKey}`);

        currentNode = currentValue;
    }
};

export const getAutoGeneratedDescription = (name: string) => {
    return `${name} commands`;
};

export const getDiscordCommandType = (type?: CommandModule["command"]["type"]) => {
    switch (type ?? "chatInput") {
        case "chatInput":
            return DiscordApplicationCommandType.ChatInput;
        case "userContextMenu":
            return DiscordApplicationCommandType.User;
        case "messageContextMenu":
            return DiscordApplicationCommandType.Message;
        case "primaryEntryPoint":
            return DiscordApplicationCommandType.PrimaryEntryPoint;
    }
};

export const createStringChoices = (argument: ApplicationCommandArguments) => {
    if (!argument.choices?.length)
        return;

    for (const choice of argument.choices) {
        if (typeof choice.value !== "string")
            throw new Error(`Invalid choice value type for option ${argument.name}. Expected string.`);
    }

    return argument.choices.map(choice => ({
        "name": choice.name,
        "value": choice.value as string
    }));
};

export const createNumberChoices = (argument: ApplicationCommandArguments) => {
    if (!argument.choices?.length)
        return;

    for (const choice of argument.choices) {
        if (typeof choice.value !== "number")
            throw new Error(`Invalid choice value type for option ${argument.name}. Expected number.`);
    }

    return argument.choices.map(choice => ({
        "name": choice.name,
        "value": choice.value as number
    }));
};

export const assertChoicesNotAllowed = (argument: ApplicationCommandArguments) => {
    if (argument.choices?.length)
        throw new Error(`Choices are not supported for option ${argument.name} of type ${argument.type}.`);
};

export const createCommandOption = (argument: ApplicationCommandArguments): BasicChatInputCommandOption => {
    const base = {
        "name": argument.name,
        "description": argument.description,
        "required": argument.required
    };

    switch (argument.type) {
        case "string":
            return {
                ...base,
                "type": DiscordApplicationCommandOptionType.String,
                "choices": createStringChoices(argument),
                "min_length": argument.minLength,
                "max_length": argument.maxLength
            };
        case "integer":
            return {
                ...base,
                "type": DiscordApplicationCommandOptionType.Integer,
                "choices": createNumberChoices(argument),
                "min_value": argument.minValue,
                "max_value": argument.maxValue
            };
        case "boolean":
            assertChoicesNotAllowed(argument);
            return {
                ...base,
                "type": DiscordApplicationCommandOptionType.Boolean
            };
        case "user":
            assertChoicesNotAllowed(argument);
            return {
                ...base,
                "type": DiscordApplicationCommandOptionType.User
            };
        case "channel":
            assertChoicesNotAllowed(argument);
            return {
                ...base,
                "type": DiscordApplicationCommandOptionType.Channel
            };
        case "role":
            assertChoicesNotAllowed(argument);
            return {
                ...base,
                "type": DiscordApplicationCommandOptionType.Role
            };
        case "mentionable":
            assertChoicesNotAllowed(argument);
            return {
                ...base,
                "type": DiscordApplicationCommandOptionType.Mentionable
            };
        case "number":
            return {
                ...base,
                "type": DiscordApplicationCommandOptionType.Number,
                "choices": createNumberChoices(argument),
                "min_value": argument.minValue,
                "max_value": argument.maxValue
            };
        case "attachment":
            assertChoicesNotAllowed(argument);
            return {
                ...base,
                "type": DiscordApplicationCommandOptionType.Attachment
            };
    }
};

export const createCommandOptions = (argumentsList?: ApplicationCommandArguments[]) => {
    if (!argumentsList?.length)
        return;

    return argumentsList.map(argument => createCommandOption(argument));
};

export const buildStandaloneCommand = (commandName: string, module: CommandModule): RESTPostAPIApplicationCommandsJSONBody => {
    const commandType = getDiscordCommandType(module.command.type);

    switch (commandType) {
        case DiscordApplicationCommandType.ChatInput:
            return {
                "type": DiscordApplicationCommandType.ChatInput,
                "name": commandName,
                "description": module.command.description,
                "options": createCommandOptions(module.command.arguments)
            };
        case DiscordApplicationCommandType.User:
            return {
                "type": DiscordApplicationCommandType.User,
                "name": commandName
            };
        case DiscordApplicationCommandType.Message:
            return {
                "type": DiscordApplicationCommandType.Message,
                "name": commandName
            };
        case DiscordApplicationCommandType.PrimaryEntryPoint:
            return {
                "type": DiscordApplicationCommandType.PrimaryEntryPoint,
                "name": commandName
            };
    }
};

export const buildSubcommandOption = (commandName: string, module: CommandModule, commandPath: string): SubcommandOption => {
    if ((module.command.type ?? "chatInput") !== "chatInput")
        throw new Error(`Nested command ${commandPath} must use chatInput type.`);

    return {
        "type": DiscordApplicationCommandOptionType.Subcommand,
        "name": commandName,
        "description": module.command.description,
        "options": createCommandOptions(module.command.arguments)
    };
};

export const buildSubcommandGroupOption = (groupName: string, tree: CommandTree, commandPath: string): SubcommandGroupOption => {
    const options = Object.entries(tree)
        .map(([subcommandName, value]) => {
            if (!isCommandModule(value))
                throw new Error(`Discord supports only one subcommand group depth. Invalid path: ${commandPath}/${subcommandName}`);

            return buildSubcommandOption(subcommandName, value, `${commandPath}/${subcommandName}`);
        });

    return {
        "type": DiscordApplicationCommandOptionType.SubcommandGroup,
        "name": groupName,
        "description": getAutoGeneratedDescription(groupName),
        "options": options
    };
};

export const buildGroupedChatInputCommand = (commandName: string, tree: CommandTree, commandPath: string): ChatInputCommandBody => {
    const options = Object.entries(tree)
        .map(([optionName, value]) => {
            if (isCommandModule(value))
                return buildSubcommandOption(optionName, value, `${commandPath}/${optionName}`);

            return buildSubcommandGroupOption(optionName, value, `${commandPath}/${optionName}`);
        });

    return {
        "type": DiscordApplicationCommandType.ChatInput,
        "name": commandName,
        "description": getAutoGeneratedDescription(commandName),
        "options": options
    };
};
